### ISSUE TITLE
xbox issue

### ISSUE THREAD

**Issue by patt1** [klinuxs/Black-Ops6#1]
Thanks for the release!
I convert the decryption for xbox in the same way as steam, but the headbone doesn't work.

it doesn't properly render the esp boxes to the players (i think becourse of the missing headbone) and when I activate skeleton I have the "headbone" rendering on cars or in the top right of the screen. very buggy. 

I don't know why but all other bones are displayed correctly.
Snaplines are under the players feet?
KMBox also works when I select chest.

Did i mess up the offsets or the decryption? BoneIDs are the same for xbox and steam?

Hope u can help me..

**Comment by patt1** [comment]
![issue](https://github.com/user-attachments/assets/6f3f7870-5538-4546-a1ec-e3a105867c35)

**Comment by klinuxs** [comment]
does it only work when they are close? if yes, its because the black ops engine is complete dogshit, if not, it is most likely a issue with bone id's
